

export const USER_ACTION_TYPES = {
    ADD_USER_INFO:'ADD_USER_INFO',
    USER_SIGN_OUT:"USER_SIGN_OUT"
}
export const UTILS_ACTION_TYPES = {
    SHOW_TOAST:'SHOW_TOAST',
    LIKE_USER:'LIKE_USER',
    DISLIKE_USER:'DISLIKE_USER'
}